TestSite/Areas/admin/Controllers/BikesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestSite.Areas.admin.ViewModels;


namespace TestSite.Areas.admin.Controllers
{
    public class BikesController : Controller
    {
        SqlConnection traincoreCon = new SqlConnection(ConfigurationManager.ConnectionStrings["traincore"].ConnectionString);
        // GET: Bikes
        public ActionResult Index()
        {
            return View("~/Areas/admin/Views/Bikes/Index.cshtml");
        }
        [HttpGet]
        public ActionResult List()
        {
            List<BikeModel> bl = new List<BikeModel>();
            SqlCommand Holidays = new SqlCommand("Select * from Bikes", traincoreCon);
            try
            {
                traincoreCon.Open();
                Holidays.Connection = traincoreCon;
                SqlDataReader rdr = Holidays.ExecuteReader();
                while (rdr.Read())
                {
                    BikeModel Bik = new BikeModel();
                    Bik.BikeID = (int)rdr["BikeID"];
                    Bik.BikeName = rdr["BikeName"].ToString();
                    Bik.BikeDetails = rdr["BikeDetails"].ToString();
                   

                    bl.Add(Bik);
                }


            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (Holidays.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }

            return View("~/Areas/admin/Views/Bikes/Index.cshtml", bl);
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<BikeModel> bik = new List<BikeModel>();
            SqlCommand Holidays = new SqlCommand("Select * from Holidays", traincoreCon);
            try
            {
                traincoreCon.Open();
                Holidays.Connection = traincoreCon;
                SqlDataReader rdr = Holidays.ExecuteReader();
                while (rdr.Read())
                {
                    BikeModel bm = new BikeModel();
                    bm.HolidayID = (int)rdr["HolidayID"];
                    bm.HolidayName = rdr["HolidayName"].ToString();

                    bik.Add(bm);
                }


            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (Holidays.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }

            return View("~/Areas/admin/Views/Bikes/Create.cshtml", bik);
        }
        
        [HttpPost]
        public ActionResult Create( string HolidayName, string BikeName, string BikeDetails, HttpPostedFileBase BikeImage, string Type, string BikeSuitability)
        {
            int HolidayID = int.Parse(Request.Form["SltHoliday"]);
            //Read the FileStream Into ByteArray, equivalent to SQL Image Data Type
            byte[] buffer = new byte[BikeImage.ContentLength];
            BikeImage.InputStream.Read(buffer, 0, BikeImage.ContentLength);


            //Setup Connection

            SqlCommand sqlInsertBike = new SqlCommand();
            sqlInsertBike.CommandText = "Insert into Bikes (HolidayID,BikeName,BikeDetails,BikeImageName,BikeImage,Type,BikeSuitability) VALUES(@HolidayID,@BikeName,@BikeDetails,@BikeImageName,@BikeImage,@Type,@BikeSuitability)";
            sqlInsertBike.Parameters.Add("@HolidayID", SqlDbType.Int).Value = HolidayID;
            sqlInsertBike.Parameters.Add("@BikeName", SqlDbType.NVarChar).Value = BikeName;
            sqlInsertBike.Parameters.Add("@BikeDetails", SqlDbType.NVarChar).Value = BikeDetails;
            sqlInsertBike.Parameters.Add("@Type", SqlDbType.NVarChar).Value = Type;
            sqlInsertBike.Parameters.Add("@BikeSuitability", SqlDbType.NVarChar).Value = BikeSuitability;

            sqlInsertBike.Parameters.Add("@BikeImageName", SqlDbType.NVarChar).Value = BikeImage.FileName;
            sqlInsertBike.Parameters.Add("@BikeImage", SqlDbType.Image).Value = buffer;
            try
            {
                traincoreCon.Open();
                sqlInsertBike.Connection = traincoreCon;
                sqlInsertBike.ExecuteNonQuery();
                ViewBag.Feedback = "Save Successfully";

            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (sqlInsertBike.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }

            return View("~/Areas/admin/Views/Bikes/Index.cshtml");
        }
        [HttpGet]
        public ActionResult Edit(int BikeID)
        {
            //Retrieve the Holiday, we are supposed to Edit and Send it on the same create Page
            //We will use SQL Reader to get the Holiday List from DB

            SqlCommand listHolidayList = new SqlCommand("Select * from Bikes where BikeID=@BikeID", traincoreCon);
            listHolidayList.Parameters.AddWithValue("@BikeID", BikeID);
            BikeModel bm = new BikeModel();
            try
            {
                traincoreCon.Open();
                listHolidayList.Connection = traincoreCon;
                SqlDataReader rdr = listHolidayList.ExecuteReader();
                while (rdr.Read())
                {

                    bm.BikeID = (int)rdr["BikeID"];
                    bm.BikeName = rdr["BikeName"].ToString();
                    bm.BikeDetails = rdr["BikeDetails"].ToString();
                    
                    
                }

            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (listHolidayList.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }
            return View("~/Areas/admin/Views/Bikes/Edit.cshtml", bm);
        }

        [HttpPost]
        public ActionResult Edit(BikeModel bkm)
        {
            //Retrieve the Holiday, we are supposed to Edit and Send it on the same create Page
            //We will use SQL Reader to get the Holiday List from DB

            SqlCommand BikeList = new SqlCommand("UPDATE Bikes SET BikeName=@BikeName, BikeDetails=@BikeDetails where BikeID=@BikeID", traincoreCon);
            BikeList.Parameters.AddWithValue("@BikeID", bkm.BikeID);
            BikeList.Parameters.AddWithValue("@BikeName", bkm.BikeName);
            BikeList.Parameters.AddWithValue("@BikeDetails", bkm.BikeDetails);

            try
            {
                traincoreCon.Open();
                BikeList.Connection = traincoreCon;
                int result = BikeList.ExecuteNonQuery();
                ViewBag.Feedback = "The record updated successfully";

            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (BikeList.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }
            return View("~/Areas/admin/Views/Bikes/Edit.cshtml");
        }
        public ActionResult Delete(int BikeID, bool? Confirm)
        {
            BikeModel bm = new BikeModel();
            if (Confirm == true)
            {
                SqlCommand cmd = new SqlCommand("Delete From Bikes where Bikeid=@BikeID");
                cmd.Parameters.Add("@BikeID", SqlDbType.Int).Value = BikeID;
                cmd.Connection = traincoreCon;
                try
                {
                    traincoreCon.Open();
                    cmd.ExecuteNonQuery();
                    ViewBag.Feedback = $"Item with {BikeID} deleted";
                }
                catch (SqlException ex)
                { ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred"; }
                catch (Exception ex)
                { ViewBag.Feedback = $"{ex.Message} occurred"; }
                finally
                {
                    if (cmd.Connection.State == ConnectionState.Open)
                    {
                        traincoreCon.Close();

                    }
                }
            }
            else
            {

                bm.BikeID = BikeID;
            }
            return View("~/Areas/admin/Views/Bikes/Delete.cshtml", bm);
        }
    }
}

TestSite/Controllers/Admin/BikesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestSite.Controllers.Admin
{
    public class BikesController : Controller
    {
        // GET: Bikes
        public ActionResult Index()
        {
            return View("~/Views/admin/Bikes/Index.cshtml");
        }
    }
}

TestSite/Areas/admin/Views/Bikes/Create.cshtml
@using TestSite.Areas.admin.ViewModels
@model List<BikeModel>
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Bikes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Label("BikeName", "Bike Name")
    @Html.TextBox("BikeName")<br />

    @Html.Label("HolidayName", "Holiday List Name")
    <select id="SltHoliday" name="SltHoliday">
        @foreach (BikeModel item in Model)
        {

            <option value="@item.HolidayID">@item.HolidayName</option>

        }
    </select>
    <br />
    @Html.Label("BikeDetails", "Bike Details")
    @Html.TextArea("BikeDetails")<br />

    @Html.Label("BikeImage", "Bike Image")
    @Html.TextBox("BikeImage", "", new { type = "file" })<br />

    @Html.Label("Type", "Type")
    @Html.TextBox("Type")<br />

    @Html.Label("BikeSuitability", "BikeSuitability")
    @Html.TextBox("BikeSuitability")<br />

    <input type="submit" value="Create Bike" />
}

TestSite/Areas/admin/Views/Bikes/Delete.cshtml
@using TestSite.Areas.admin.ViewModels
@model BikeModel
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.Feedback != null)
{
    <h1>@ViewBag.Feedback</h1>
    @Html.ActionLink("Back to List", "List", "Bikes")
}
else
{

    if (Model != null)
    {
        <h2>Are you sure you want to Delete</h2>
        @Html.ActionLink("Delete", "Delete", "Bikes", new { BikeID = Model.BikeID, Confirm = true }, null)
        @Html.ActionLink("Cancel", "List", "Bikes")
        @Model.BikeID
    }
    else
    {
        <span>There is nothing to delete, Please go back and select again.</span>
    }

}

TestSite/Areas/admin/Views/Bikes/Edit.cshtml
@using TestSite.Areas.admin.ViewModels
@model BikeModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@if (ViewBag.Feedback != null)
{
    <h1>@ViewBag.Feedback</h1>
    @Html.ActionLink("Back to List", "List", "Bikes")
}
else
{

    if (Model != null)
    {
    <h2>Edit Bike List here</h2>
        using (Html.BeginForm("Edit", "Bikes", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.Label("BikeID");
            @Html.TextBox("BikeID", Model.BikeID, new { @readonly = "readonly" })<br />

            @Html.Label("BikeName", "Bike Name")
            @Html.TextBox("BikeName", Model.BikeName)<br />

            @Html.Label("BikeDetails", "Bike Details")
            @Html.TextArea("BikeDetails", Model.BikeDetails)<br />

            <input type="submit" value="Update Bike List" />
        }
    }
    else
    {
        <h2>There is nothing to Edit here</h2>
        <p>Please go back to the list and try again:@Html.ActionLink("Back to List", "List", "Bikes")</p>

    }
}

TestSite/Areas/admin/Views/Bikes/Index.cshtml
@using TestSite.Areas.admin.ViewModels
@model List<BikeModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
Manage Bikes Here!

<ul>
    <li>@Html.ActionLink("View Bikes", "List", "Bikes")</li>
    <li>@Html.ActionLink("Create Bike", "Create", "Bikes")</li>

</ul>

@if (Model != null)
{
    <h2>Bike Lists</h2>
    foreach (BikeModel bik in Model)
    {
        <div>
            <ul>
                <li>
                    @bik.BikeName
                    <span>@Html.ActionLink("Delete", "Delete", "Bikes", new { BikeID = bik.BikeID, Confirm = false }, null)</span>
                    <span>@Html.ActionLink("Edit", "Edit", "Bikes", new { BikeID = bik.BikeID }, null)</span>
                </li>
            </ul>
        </div>
    }
}

TestSite/Areas/admin/Views/Bikes/List.cshtml
@model IEnumerable<TestSite.Areas.admin.ViewModels.BikeModel>

@{
    ViewBag.Title = "List";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BikeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeDetails)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.BikeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BikeDetails)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new {  BikeID=item.BikeID }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKe*/ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>