TestSite/Areas/admin/Controllers/HolidaysController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestSite.Areas.admin.ViewModels;

namespace TestSite.Areas.admin.Controllers
{
    public class HolidaysController : Controller
    {
        SqlConnection traincoreCon = new SqlConnection(ConfigurationManager.ConnectionStrings["traincore"].ConnectionString);
        // GET: Holidays
        public ActionResult Index()
        {          
            return View("~/Areas/admin/Views/Holidays/Index.cshtml");
        }
        [HttpGet]
        public ActionResult List()
        {
            List<HolidaysModel> hl = new List<HolidaysModel>();
            SqlCommand listHolidayList = new SqlCommand("Select * from Holidays", traincoreCon);
            try
            {
                traincoreCon.Open();
                listHolidayList.Connection = traincoreCon;
                SqlDataReader rdr = listHolidayList.ExecuteReader();
                while (rdr.Read())
                {
                    HolidaysModel hm = new HolidaysModel();
                    hm.HolidayID = (int)rdr["HolidayID"];
                    hm.HolidayListID = (int)rdr["HolidayListID"];
                    hm.HolidayName = rdr["HolidayName"].ToString();
                    hm.HolidayDetails = rdr["HolidayDetails"].ToString();
                    hm.HolidayImageName = rdr["HolidayDetails"].ToString();
                    hm.StartDate = (DateTime)rdr["StartDate"];
                    hm.PricePerPerson = (decimal)rdr["PricePerPerson"];
                    if (rdr["HolidayImage"] != DBNull.Value)
                    {
                        hm.HolidayImage = (byte[])rdr["HolidayImage"];
                    }

                    hl.Add(hm);
                }
                ViewBag.Feedback = "Save Successfully";

            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (listHolidayList.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }

            return View("~/Areas/admin/Views/Holidays/Index.cshtml", hl);
        }


        //Need Get to receive empty form 
        [HttpGet]
        public ActionResult Create(HolidayListsModel hlm)
        {
            List<HolidayListsModel> hl = new List<HolidayListsModel>();
            SqlCommand listHolidayList = new SqlCommand("Select HolidayListID,HolidayListName from HolidayLists", traincoreCon);
            try
            {
                traincoreCon.Open();
                listHolidayList.Connection = traincoreCon;
                SqlDataReader rdr = listHolidayList.ExecuteReader();
                while (rdr.Read())
                {
                    HolidayListsModel hm = new HolidayListsModel();
                    hm.HolidayListID = (int)rdr["HolidayListID"];
                    hm.HolidayListName = rdr["HolidayListName"].ToString();                              
                    hl.Add(hm);
                }             
            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (listHolidayList.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }
            return View("~/Areas/admin/Views/Holidays/Create.cshtml",hl);
        }
        [HttpPost]
        public ActionResult Create( string HolidayName, string HolidayDetails,DateTime? StartDate,decimal? PricePerPerson, HttpPostedFileBase HolidayImage)
        {
            //Read the FileStream Into ByteArray, equivalent to SQL Image Data Type
            byte[] buffer = new byte[HolidayImage.ContentLength];
            HolidayImage.InputStream.Read(buffer, 0, HolidayImage.ContentLength);

            int HolidayListID = int.Parse(Request.Form["holidaylist"].ToString());
            //Setup Connection

            SqlCommand sqlInsertHolidayList = new SqlCommand();
            sqlInsertHolidayList.CommandText = "Insert into Holidays (HolidayListID,HolidayName,HolidayDetails,HolidayImageName,HolidayImage,StartDate,PricePerPerson) VALUES(@HolidayListID,@HolidayName,@HolidayDetails,@HolidayImageName,@HolidayImage,@StartDate,@PricePerPerson)";
            sqlInsertHolidayList.Parameters.Add("@HolidayListID", SqlDbType.Int).Value = HolidayListID;
            sqlInsertHolidayList.Parameters.Add("@HolidayName", SqlDbType.NVarChar, 256).Value = HolidayName;
            sqlInsertHolidayList.Parameters.Add("@HolidayDetails", SqlDbType.NVarChar, 256).Value = HolidayDetails;
            sqlInsertHolidayList.Parameters.Add("@HolidayImageName", SqlDbType.NVarChar, 250).Value = HolidayImage.FileName;
            sqlInsertHolidayList.Parameters.Add("@HolidayImage", SqlDbType.Image).Value = buffer;
            sqlInsertHolidayList.Parameters.Add("@StartDate", SqlDbType.Date).Value = StartDate;
            sqlInsertHolidayList.Parameters.Add("@PricePerPerson", SqlDbType.Money).Value = PricePerPerson;
            try
            {
                traincoreCon.Open();
                sqlInsertHolidayList.Connection = traincoreCon;
                sqlInsertHolidayList.ExecuteNonQuery();
                ViewBag.Feedback = "Save Successfully";

            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (sqlInsertHolidayList.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }

            return View("~/Areas/admin/Views/Holidays/Create.cshtml");
        }
        [HttpGet]
        public ActionResult Edit(int HolidayID)
        {
            //Retrieve the Holiday, we are supposed to Edit and Send it on the same create Page
            //We will use SQL Reader to get the Holiday List from DB

            SqlCommand listHolidayList = new SqlCommand("Select * from Holidays where HolidayID=@HolidayID", traincoreCon);
            listHolidayList.Parameters.AddWithValue("@HolidayID", HolidayID);
            HolidaysModel hm = new HolidaysModel();
            try
            {
                traincoreCon.Open();
                listHolidayList.Connection = traincoreCon;
                SqlDataReader rdr = listHolidayList.ExecuteReader();
                while (rdr.Read())
                {

                    hm.HolidayID= (int)rdr["HolidayID"];
                    hm.HolidayName = rdr["HolidayName"].ToString();
                    hm.HolidayDetails = rdr["HolidayDetails"].ToString();
                    hm.HolidayImageName = rdr["HolidayImageName"].ToString();
                    if (rdr["HolidayImage"] != DBNull.Value)
                    {
                        hm.HolidayImage = (byte[])rdr["HolidayImage"];
                    }
                }

            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (listHolidayList.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }
            return View("~/Areas/admin/Views/Holidays/Edit.cshtml", hm);
        }

        [HttpPost]
        public ActionResult Edit(HolidaysModel hlm)
        {
            //Retrieve the Holiday, we are supposed to Edit and Send it on the same create Page
            //We will use SQL Reader to get the Holiday List from DB

            SqlCommand listHolidayList = new SqlCommand("UPDATE Holidays SET HolidayName=@HolidayName, StartDate=@StartDate, HolidayDetails=@HolidayDetails,PricePerPerson=@PricePerPerson where HolidayID=@HolidayID", traincoreCon);
            listHolidayList.Parameters.AddWithValue("@HolidayID", hlm.HolidayID);
            listHolidayList.Parameters.AddWithValue("@HolidayName", hlm.HolidayName);
            listHolidayList.Parameters.AddWithValue("@HolidayDetails", hlm.HolidayDetails);
            listHolidayList.Parameters.AddWithValue("@StartDate", hlm.StartDate);
            listHolidayList.Parameters.AddWithValue("@PricePerPerson", hlm.PricePerPerson);
            try
            {
                traincoreCon.Open();
                listHolidayList.Connection = traincoreCon;
                int result = listHolidayList.ExecuteNonQuery();
                ViewBag.Feedback = "The record updated successfully";

            }
            catch (SqlException ex)
            {
                ViewBag.Feedback = $"{ex.ErrorCode}, {ex.Message} occurred";
            }
            catch (Exception ex)
            {
                ViewBag.Feedback = $"{ex.Message} occurred";
            }
            finally
            {
                if (listHolidayList.Connection.State == ConnectionState.Open)
                {
                    traincoreCon.Close();
                }
            }
            return View("~/Areas/admin/Views/Holidays/Edit.cshtml");
        }


        public ActionResult Delete(int HolidayID, bool? Confirm)
        {

TestSite/Controllers/Admin/HolidaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestSite.Controllers.Admin
{
    public class HolidaysController : Controller
    {
        // GET: Holidays
        public ActionResult Index()
        {
            return View("~/Views/admin/Holidays/Index.cshtml");
        }
    }
}

TestSite/Areas/admin/Views/Holidays/Create.cshtml
@using TestSite.Areas.admin.ViewModels
@model List<HolidayListsModel>

@{
    ViewBag.Title = "Create";
}


<h2>Create</h2>

@if (ViewBag.Feedback != null)
{
    <strong>@ViewBag.Feedback</strong>
}

else
{
    using (Html.BeginForm("Create", "Holidays", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.Label("HolidayName", "Holiday Name")
        <select class="form-control"id="ddlViewBy" name="holidaylist">
            <option>Select HolidayList</option>
            @foreach (HolidayListsModel hlm in Model)
            {
                <option value="@hlm.HolidayListID">@hlm.HolidayListName</option>

            }
        </select> <br />

        
        @*@Html.TextBox("HolidayListID", @ViewBag.Id, new { @class = "hidden" })<br />*@

        @Html.Label("HolidayName", "Holiday Name")
        @Html.TextBox("HolidayName")<br />

        @Html.Label("HolidayDetails", "Holiday List Details")
        @Html.TextArea("HolidayDetails")<br />

        @Html.Label("StartDate", "Holiday Start Date")
        @Html.TextBox("StartDate") <br />

        @Html.Label("PricePerPerson", "Price Per Person")
        @Html.TextBox("PricePerPerson")<br />

        @Html.Label("HolidayImage", "Holiday Image")
        @Html.TextBox("HolidayImage", "", new { type = "file" })<br />



        <input type="submit" value="Create Holiday" />
    }

}

TestSite/Areas/admin/Views/Holidays/Delete.cshtml
@using TestSite.Areas.admin.ViewModels
@model HolidaysModel
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
@if (ViewBag.Feedback != null)
{
    <h1>@ViewBag.Feedback</h1>
    @Html.ActionLink("Back to List", "List", "Holidays")
}
else
{

    if (Model != null)
    {
        <h2>Are you sure you want to Delete</h2>
        @Html.ActionLink("Delete", "Delete", "Holidays", new { HolidayID = Model.HolidayID, Confirm = true }, null)
        @Html.ActionLink("Cancel", "List", "Holidays")
        @Model.HolidayID
    }
    else
    {
        <span>There is nothing to delete, Please go back and select again.</span>
    }

}

TestSite/Areas/admin/Views/Holidays/Edit.cshtml
@using TestSite.Areas.admin.ViewModels
@model HolidaysModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@if (ViewBag.Feedback != null)
{
    <h1>@ViewBag.Feedback</h1>
    @Html.ActionLink("Back to List", "List", "Holidays")
}
else
{

    if (Model != null)
    {
        <h2>Edit Holiday List here</h2>
        using (Html.BeginForm("Edit", "Holidays", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.Label("HolidayID");
            @Html.TextBox("HolidayID", Model.HolidayListID, new { @readonly = "readonly" })<br />

            @Html.Label("HolidayName", "Holiday  Name")
            @Html.TextBox("HolidayName", Model.HolidayName)<br />

            @Html.Label("HolidayDetails", "Holiday Details")
            @Html.TextArea("HolidayDetails", Model.HolidayDetails)<br />

            @Html.Label("StartDate", "Holiday Start Date")
            @Html.TextArea("StartDate", Model.StartDate)<br />

            @Html.Label("PricePerPerson", "Price Per Person")
            @Html.TextArea("PricePerPerson", Model.PricePerPerson)<br />

            <input type="submit" value="Edit Holiday" />
        }
    }
    else
    {
        <h2>There is nothing to Edit here</h2>
        <p>Please go back to the list and try again:@Html.ActionLink("Back to List", "List", "Holidays")</p>

    }
}

TestSite/Areas/admin/Views/Holidays/Index.cshtml
@using TestSite.Areas.admin.ViewModels
@model List<HolidaysModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
List All Holidays Here!

<ul>
    <li>@Html.ActionLink("View Holidays", "List", "Holidays")</li>
    <li>@Html.ActionLink("Create Holidays ", "Create", "Holidays")</li>

</ul>

@if (Model != null)
    {
        <h2>Holidays Lists</h2>
        foreach (HolidaysModel hlm in Model)
        {
            <div>
                <ul>
                    <li>
                        @hlm.HolidayName
                        <span>@Html.ActionLink("Delete", "Delete", "Holidays", new { HolidayID = hlm.HolidayID }, null)</span>
                        <span>@Html.ActionLink("Edit", "Edit", "Holidays", new { HolidayID = hlm.HolidayID }, null)</span>
                    </li>
                </ul>
            </div>
    }
}
else
{
    <p>Nothing to show here</p>
}